module.exports = {
    " ability ": " capability ",
    " able ": " capable ",
    " about ": " regarding ",
    " above ": " over ",
    " accept ": " agree to ",
    " according ": " as per ",
    " across ": " over ",
    " act ": " perform ",
    " action ": " activity ",
    " activity ": " action ",
    " actually ": " in reality ",
    " add ": " include ",
    " administration ": " government ",
    " adult ": " grown-up ",
    " affect ": " influence ",
    " after ": " following ",
    " again ": " once more ",
    " against ": " opposed to ",
    " age ": " era ",
    " agency ": " organization ",
    " ago ": " before ",
    " agree ": " consent ",
    " air ": " atmosphere ",
    " all ": " every ",
    " allow ": " permit ",
    " almost ": " nearly ",
    " along ": " together ",
    " already ": " previously ",
    " also ": " in addition ",
    " although ": " even though ",
    " always ": " at all times ",
    " american ": " us ",
    " among ": " amongst ",
    " amount ": " quantity ",
    " analysis ": " examination ",
    " and ": " also ",
    " animal ": " creature ",
    " another ": " additional ",
    " answer ": " reply ",
    " any ": " any ",
    " anyone ": " anybody ",
    " anything ": " something ",
    " appear ": " seem ",
    " apply ": " utilize ",
    " approach ": " method ",
    " area ": " region ",
    " argue ": " dispute ",
    " arm ": " limb ",
    " around ": " approximately ",
    " arrive ": " come ",
    " art ": " fine art ",
    " article ": " piece ",
    " artist ": " painter ",
    " as ": " as ",
    " ask ": " inquire ",
    " attack ": " assault ",
    " attention ": " focus ",
    " author ": " writer ",
    " authority ": " power ",
    " available ": " accessible ",
    " avoid ": " prevent ",
    " away ": " far ",
    " baby ": " infant ",
    " back ": " rear ",
    " bad ": " negative ",
    " ball ": " sphere ",
    " bank ": " financial institution ",
    " bar ": " pub ",
    " base ": " foundation ",
    " be ": " exist ",
    " beautiful ": " gorgeous ",
    " because ": " due to ",
    " become ": " transform into ",
    " bed ": " sleeping ",
    " before ": " prior to ",
    " begin ": " commence ",
    " behavior ": " conduct ",
    " behind ": " in the rear ",
    " believe ": " trust ",
    " benefit ": " advantage ",
    " best ": " optimal ",
    " better ": " improved ",
    " between ": " in the middle of ",
    " beyond ": " outside ",
    " big ": " large ",
    " bill ": " invoice ",
    " billion ": " 1,000 million ",
    " bit ": " fragment ",
    " black ": " dark ",
    " blood ": " circulation ",
    " blue ": " azure ",
    " board ": " panel ",
    " body ": " physique ",
    " book ": " volume ",
    " both ": " two ",
    " box ": " container ",
    " boy ": " lad ",
    " break ": " pause ",
    " bring ": " convey ",
    " brother ": " sibling ",
    " browser ": " explorer ",
    " build ": " construct ",
    " building ": " structure ",
    " business ": " enterprise ",
    " but ": " however ",
    " buy ": " purchase ",
    " by ": " by ",
    " call ": " phone ",
    " camera ": " photographic device ",
    " campaign ": " election ",
    " can ": " be able to ",
    " can't ": " cannot ",
    " candidate ": " contender ",
    " car ": " automobile ",
    " card ": " playing card ",
    " care ": " nurture ",
    " career ": " profession ",
    " carry ": " transport ",
    " case ": " instance ",
    " cause ": " reason ",
    " cell ": " unit ",
    " center ": " middle ",
    " central ": " middle ",
    " century ": " 100 years ",
    " certain ": " specific ",
    " certainly ": " definitely ",
    " chair ": " preside over ",
    " challenge ": " obstacle ",
    " chance ": " opportunity ",
    " change ": " alter ",
    " character ": " personality ",
    " charge ": " fee ",
    " check ": " verify ",
    " child ": " offspring ",
    " choice ": " selection ",
    " choose ": " select ",
    " church ": " religious institution ",
    " city ": " metropolis ",
    " claim ": " assertion ",
    " class ": " course ",
    " clear ": " transparent ",
    " clearly ": " obviously ",
    " close ": " shut ",
    " cold ": " chilly ",
    " college ": " university ",
    " color ": " hue ",
    " come ": " arrive ",
    " common ": " ordinary ",
    " community ": " society ",
    " company ": " business ",
    " compare ": " contrast ",
    " computer ": " pc ",
    " concern ": " worry ",
    " condition ": " state ",
    " conference ": " convention ",
    " congress ": " legislature ",
    " consider ": " contemplate ",
    " contain ": " hold ",
    " continue ": " persist ",
    " control ": " manage ",
    " cost ": " expense ",
    " could ": " be able to ",
    " country ": " nation ",
    " couple ": " pair ",
    " course ": " program ",
    " court ": " tribunal ",
    " cover ": " protect ",
    " create ": " make ",
    " crime ": " offense ",
    " cultural ": " cultural ",
    " culture ": " society ",
    " cup ": " mug ",
    " current ": " present ",
    " cut ": " slice ",
    " dark ": " dim ",
    " daughter ": " female child ",
    " day ": " 24 hours ",
    " dead ": " lifeless ",
    " deal ": " agreement ",
    " death ": " demise ",
    " decade ": " 10 years ",
    " decide ": " determine ",
    " decision ": " choice ",
    " deep ": " profound ",
    " defense ": " protection ",
    " degree ": " level ",
    " democrat ": " democratic party ",
    " democratic ": " representative ",
    " describe ": " explain ",
    " design ": " create ",
    " despite ": " in spite of ",
    " determine ": " decide ",
    " develop ": " evolve ",
    " development ": " growth ",
    " die ": " expire ",
    " difference ": " disparity ",
    " different ": " distinct ",
    " difficult ": " challenging ",
    " direction ": " course ",
    " director ": " manager ",
    " discover ": " unearth ",
    " discuss ": " talk about ",
    " disease ": " illness ",
    " do ": " perform ",
    " doctor ": " physician ",
    " dog ": " canine ",
    " door ": " entrance ",
    " down ": " lower ",
    " draw ": " sketch ",
    " dream ": " aspiration ",
    " drive ": " operate ",
    " drop ": " fall ",
    " drug ": " medication ",
    " during ": " in the course of ",
    " each ": " every ",
    " early ": " premature ",
    " east ": " eastern ",
    " easy ": " simple ",
    " eat ": " consume ",
    " economic ": " financial ",
    " economy ": " economic system ",
    " edge ": " boundary ",
    " education ": " learning ",
    " effect ": " impact ",
    " effort ": " attempt ",
    " eight ": " 8 ",
    " either ": " or ",
    " election ": " vote ",
    " employee ": " worker ",
    " end ": " conclusion ",
    " energy ": " power ",
    " enjoy ": " savor ",
    " enough ": " sufficient ",
    " enter ": " join ",
    " entire ": " whole ",
    " environment ": " surroundings ",
    " environmental ": " ecological ",
    " especially ": " particularly ",
    " establish ": " found ",
    " even ": " inclusive ",
    " evening ": " nighttime ",
    " event ": " occasion ",
    " ever ": " at any time ",
    " every ": " each ",
    " everybody ": " everyone ",
    " everyone ": " everybody ",
    " everything ": " all ",
    " evidence ": " proof ",
    " exactly ": " precisely ",
    " example ": " instance ",
    " executive ": " managerial ",
    " expect ": " anticipate ",
    " experience ": " encounter ",
    " expert ": " specialist ",
    " explain ": " clarify ",
    " eye ": " organ ",
    " face ": " countenance ",
    " fact ": " reality ",
    " factor ": " element ",
    " fail ": " be unsuccessful ",
    " fall ": " descend ",
    " family ": " relatives ",
    " far ": " distant ",
    " father ": " parent ",
    " fear ": " dread ",
    " federal ": " national ",
    " feel ": " experience ",
    " feeling ": " emotion ",
    " few ": " not many ",
    " field ": " area ",
    " fight ": " battle ",
    " figure ": " shape ",
    " fill ": " occupy ",
    " film ": " movie ",
    " final ": " last ",
    " finally ": " ultimately ",
    " financial ": " monetary ",
    " find ": " discover ",
    " fine ": " excellent ",
    " finish ": " complete ",
    " fire ": " burn ",
    " firm ": " company ",
    " first ": " initial ",
    " fish ": " angle ",
    " five ": " 5 ",
    " floor ": " ground ",
    " fly ": " soar ",
    " focus ": " concentrate ",
    " follow ": " pursue ",
    " food ": " nourishment ",
    " foot ": " lower extremity ",
    " force ": " power ",
    " foreign ": " international ",
    " forget ": " overlook ",
    " form ": " shape ",
    " former ": " previous ",
    " forward ": " ahead ",
    " four ": " 4 ",
    " free ": " liberate ",
    " friend ": " companion ",
    " from ": " from ",
    " front ": " forefront ",
    " full ": " complete ",
    " fund ": " finance ",
    " future ": " upcoming ",
    " game ": " contest ",
    " general ": " universal ",
    " get ": " obtain ",
    " girl ": " young woman ",
    " give ": " provide ",
    " glass ": " container ",
    " go ": " proceed ",
    " goal ": " objective ",
    " good ": " positive ",
    " government ": " administration ",
    " great ": " excellent ",
    " green ": " emerald ",
    " ground ": " earth ",
    " group ": " collection ",
    " grow ": " develop ",
    " growth ": " development ",
    " guess ": " estimate ",
    " gun ": " firearm ",
    " guy ": " man ",
    " hair ": " strand ",
    " half ": " 50 percent ",
    " hand ": " hand ",
    " hang ": " suspend ",
    " happen ": " occur ",
    " happy ": " joyful ",
    " hard ": " difficult ",
    " have ": " possess ",
    " he ": " he ",
    " head ": " chief ",
    " health ": " wellness ",
    " hear ": " listen to ",
    " heart ": " core ",
    " help ": " assist ",
    " her ": " hers ",
    " here ": " in this place ",
    " herself ": " her own ",
    " high ": " tall ",
    " him ": " himself ",
    " himself ": " self ",
    " his ": " his ",
    " history ": " past ",
    " hit ": " strike ",
    " hold ": " grasp ",
    " home ": " residence ",
    " hope ": " wish ",
    " hospital ": " medical center ",
    " hot ": " heated ",
    " hour ": " 60 minutes ",
    " house ": " dwelling ",
    " how ": " in what way ",
    " however ": " nevertheless ",
    " huge ": " enormous ",
    " human ": " person ",
    " hundred ": " 100 ",
    " husband ": " spouse ",
    " i ": " i ",
    " idea ": " concept ",
    " identify ": " recognize ",
    " imagine ": " envision ",
    " impact ": " influence ",
    " important ": " significant ",
    " improve ": " enhance ",
    " include ": " incorporate ",
    " including ": " inclusive of ",
    " increase ": " raise ",
    " indeed ": " certainly ",
    " indicate ": " show ",
    " individual ": " person ",
    " industry ": " sector ",
    " information ": " data ",
    " inside ": " within ",
    " instead ": " alternatively ",
    " institution ": " organization ",
    " interest ": " curiosity ",
    " international ": " global ",
    " interview ": " conduct an interview with ",
    " into ": " within ",
    " involve ": " engage ",
    " issue ": " problem ",
    " it ": " it ",
    " its ": " belonging to it ",
    " itself ": " on its own ",
    " job ": " occupation ",
    " join ": " unite ",
    " just ": " merely ",
    " keep ": " retain ",
    " kid ": " child ",
    " kill ": " slay ",
    " kind ": " type ",
    " know ": " have knowledge of ",
    " knowledge ": " information ",
    " land ": " territory ",
    " language ": " speech ",
    " large ": " big ",
    " last ": " final ",
    " late ": " delayed ",
    " later ": " afterward ",
    " laugh ": " giggle ",
    " law ": " legislation ",
    " lawyer ": " attorney ",
    " lay ": " place ",
    " lead ": " guide ",
    " leader ": " chief ",
    " learn ": " study ",
    " least ": " smallest ",
    " leave ": " depart ",
    " left ": " opposite of right ",
    " leg ": " limb ",
    " legal ": " lawful ",
    " less ": " smaller ",
    " letter ": " correspondence ",
    " level ": " degree ",
    " lie ": " fib ",
    " life ": " existence ",
    " light ": " illumination ",
    " like ": " similar to ",
    " likely ": " probable ",
    " line ": " queue ",
    " list ": " inventory ",
    " listen ": " hear ",
    " little ": " small ",
    " live ": " reside ",
    " local ": " community ",
    " long ": " lengthy ",
    " look ": " gaze ",
    " lose ": " misplace ",
    " loss ": " defeat ",
    " lot ": " many ",
    " love ": " adore ",
    " low ": " subdued ",
    " main ": " primary ",
    " maintain ": " preserve ",
    " major ": " significant ",
    " make ": " create ",
    " man ": " male ",
    " manage ": " oversee ",
    " management ": " administration ",
    " manager ": " supervisor ",
    " many ": " numerous ",
    " market ": " marketplace ",
    " material ": " substance ",
    " matter ": " issue ",
    " may ": " might ",
    " maybe ": " perhaps ",
    " me ": " myself ",
    " mean ": " signify ",
    " measure ": " quantify ",
    " media ": " press ",
    " medical ": " healthcare ",
    " meet ": " encounter ",
    " meeting ": " gathering ",
    " member ": " part ",
    " memory ": " recollection ",
    " mention ": " reference ",
    " message ": " message ",
    " middle ": " center ",
    " might ": " possibility ",
    " military ": " armed forces ",
    " million ": " 1,000,000 ",
    " mind ": " thoughts ",
    " minute ": " moment ",
    " miss ": " fail to catch ",
    " model ": " example ",
    " moment ": " instant ",
    " money ": " currency ",
    " month ": " calendar month ",
    " more ": " additional ",
    " morning ": " a.m. ",
    " most ": " majority ",
    " mother ": " female parent ",
    " move ": " relocate ",
    " movement ": " motion ",
    " movie ": " film ",
    " mr. ": " mister ",
    " much ": " a lot ",
    " music ": " melody ",
    " must ": " need to ",
    " my ": " mine ",
    " myself ": " me ",
    " name ": " title ",
    " nation ": " country ",
    " national ": " nationwide ",
    " natural ": " organic ",
    " nature ": " natural world ",
    " near ": " close to ",
    " nearly ": " almost ",
    " necessary ": " essential ",
    " need ": " requirement ",
    " network ": " system ",
    " never ": " not once ",
    " news ": " information ",
    " next ": " following ",
    " nice ": " pleasant ",
    " night ": " evening ",
    " no ": " not any ",
    " north ": " northern ",
    " not ": " negation ",
    " note ": " observe ",
    " nothing ": " zero ",
    " number ": " quantity ",
    " occur ": " happen ",
    " of ": " from ",
    " off ": " not on ",
    " offer ": " present ",
    " office ": " workplace ",
    " officer ": " official ",
    " official ": " authorized ",
    " often ": " often ",
    " oh ": " ah ",
    " oil ": " petroleum ",
    " ok ": " acceptable ",
    " old ": " elderly ",
    " on ": " upon ",
    " once ": " one time ",
    " one ": " a single ",
    " only ": " solely ",
    " onto ": " on ",
    " open ": " unlocked ",
    " operation ": " procedure ",
    " opportunity ": " chance ",
    " or ": " alternatively ",
    " order ": " sequence ",
    " organization ": " group ",
    " other ": " different ",
    " others ": " different ",
    " our ": " belonging to us ",
    " out ": " outside ",
    " outside ": " outdoors ",
    " over ": " above ",
    " own ": " possess ",
    " page ": " sheet ",
    " pain ": " ache ",
    " paper ": " document ",
    " parent ": " mother/father ",
    " part ": " portion ",
    " particular ": " specific ",
    " particularly ": " especially ",
    " party ": " celebration ",
    " pass ": " succeed ",
    " past ": " previous ",
    " patient ": " person in need of care ",
    " pay ": " remunerate ",
    " peace ": " tranquility ",
    " people ": " individuals ",
    " per ": " each ",
    " perform ": " execute ",
    " performance ": " show ",
    " perhaps ": " maybe ",
    " period ": " time span ",
    " person ": " individual ",
    " personal ": " individual ",
    " phone ": " telephone ",
    " physical ": " bodily ",
    " pick ": " choose ",
    " picture ": " image ",
    " piece ": " part ",
    " place ": " location ",
    " plan ": " scheme ",
    " plant ": " vegetation ",
    " play ": " perform ",
    " player ": " performer ",
    " pm ": " prime minister ",
    " point ": " dot ",
    " police ": " law enforcement ",
    " policy ": " procedure ",
    " political ": " politic ",
    " politics ": " governance ",
    " poor ": " needy ",
    " popular ": " well-liked ",
    " population ": " people ",
    " position ": " placement ",
    " possible ": " feasible ",
    " power ": " authority ",
    " practice ": " exercise ",
    " prepare ": " ready ",
    " present ": " current ",
    " president ": " chief executive ",
    " pressure ": " force ",
    " pretty ": " beautiful ",
    " price ": " cost ",
    " private ": " personal ",
    " probably ": " likely ",
    " problem ": " issue ",
    " process ": " procedure ",
    " produce ": " manufacture ",
    " product ": " item ",
    " production ": " manufacturing ",
    " professor ": " teacher ",
    " program ": " programme ",
    " project ": " undertaking ",
    " property ": " possession ",
    " protect ": " shield ",
    " prove ": " demonstrate ",
    " provide ": " supply ",
    " public ": " community ",
    " pull ": " tug ",
    " push ": " shove ",
    " put ": " place ",
    " quality ": " attribute ",
    " question ": " query ",
    " quickly ": " rapidly ",
    " quite ": " fairly ",
    " race ": " competition ",
    " radio ": " wireless ",
    " raise ": " increase ",
    " range ": " scope ",
    " rate ": " speed ",
    " rather ": " instead ",
    " reach ": " achieve ",
    " read ": " peruse ",
    " ready ": " prepared ",
    " real ": " genuine ",
    " realize ": " recognize ",
    " really ": " truly ",
    " reason ": " cause ",
    " receive ": " get ",
    " recent ": " new ",
    " recently ": " lately ",
    " recognize ": " acknowledge ",
    " red ": " crimson ",
    " reduce ": " decrease ",
    " region ": " area ",
    " relationship ": " connection ",
    " religious ": " spiritual ",
    " remain ": " stay ",
    " remember ": " recall ",
    " remove ": " eliminate ",
    " report ": " document ",
    " represent ": " depict ",
    " republican ": " gop ",
    " require ": " demand ",
    " research ": " investigation ",
    " resource ": " asset ",
    " respond ": " answer ",
    " response ": " reply ",
    " rest ": " relax ",
    " result ": " result ",
    " reveal ": " disclose ",
    " rise ": " increase ",
    " risk ": " danger ",
    " road ": " street ",
    " rock ": " stone ",
    " role ": " part ",
    " room ": " chamber ",
    " rule ": " regulation ",
    " run ": " operate ",
    " same ": " identical ",
    " save ": " rescue ",
    " say ": " express ",
    " scene ": " setting ",
    " school ": " educational institution ",
    " science ": " scientific study ",
    " sea ": " ocean ",
    " season ": " time of year ",
    " seat ": " chair ",
    " second ": " moment ",
    " section ": " part ",
    " security ": " safety ",
    " see ": " perceive ",
    " seek ": " search for ",
    " seem ": " appear ",
    " sell ": " trade ",
    " send ": " dispatch ",
    " sense ": " perception ",
    " series ": " sequence ",
    " serious ": " grave ",
    " serve ": " provide ",
    " service ": " assistance ",
    " set ": " collection ",
    " seven ": " 7 ",
    " several ": " various ",
    " sex ": " gender ",
    " shake ": " tremble ",
    " share ": " divide ",
    " she ": " she ",
    " shoot ": " fire ",
    " short ": " brief ",
    " should ": " ought to ",
    " shoulder ": " bear ",
    " show ": " display ",
    " side ": " aspect ",
    " sign ": " symbol ",
    " significant ": " important ",
    " similar ": " alike ",
    " simple ": " easy ",
    " simply ": " just ",
    " since ": " because ",
    " single ": " individual ",
    " sister ": " female sibling ",
    " sit ": " be seated ",
    " site ": " location ",
    " situation ": " circumstance ",
    " six ": " 6 ",
    " size ": " size ",
    " skill ": " ability ",
    " small ": " little ",
    " so ": " thus ",
    " social ": " societal ",
    " society ": " community ",
    " some ": " certain ",
    " someone ": " somebody ",
    " something ": " a thing ",
    " sometimes ": " occasionally ",
    " son ": " male child ",
    " song ": " music ",
    " soon ": " shortly ",
    " sort ": " classify ",
    " sound ": " noise ",
    " source ": " origin ",
    " south ": " southern ",
    " space ": " room ",
    " speak ": " talk ",
    " special ": " unique ",
    " specific ": " particular ",
    " spend ": " consume ",
    " sport ": " game ",
    " spring ": " season ",
    " staff ": " personnel ",
    " stage ": " phase ",
    " stand ": " upright ",
    " standard ": " norm ",
    " star ": " celebrity ",
    " start ": " commence ",
    " started ": " began ",
    " state ": " condition ",
    " statement ": " declaration ",
    " station ": " stop ",
    " stay ": " remain ",
    " step ": " stride ",
    " still ": " yet ",
    " stock ": " inventory ",
    " stop ": " halt ",
    " store ": " shop ",
    " story ": " tale ",
    " strategy ": " plan ",
    " street ": " road ",
    " strong ": " powerful ",
    " structure ": " framework ",
    " student ": " learner ",
    " study ": " research ",
    " stuff ": " things ",
    " style ": " fashion ",
    " subject ": " topic ",
    " success ": " achievement ",
    " such ": " like ",
    " suddenly ": " abruptly ",
    " suggest ": " propose ",
    " summer ": " season ",
    " support ": " help ",
    " sure ": " certain ",
    " system ": " framework ",
    " table ": " chart ",
    " take ": " seize ",
    " talk ": " speak ",
    " tax ": " levy ",
    " teach ": " instruct ",
    " teacher ": " educator ",
    " team ": " group ",
    " technology ": " innovation ",
    " television ": " tv ",
    " tell ": " inform ",
    " ten ": " 10 ",
    " term ": " word ",
    " test ": " examine ",
    " than ": " compared to ",
    " thank ": " express gratitude ",
    " that ": " that ",
    " their ": " their ",
    " them ": " those individuals ",
    " themselves ": " self ",
    " then ": " at that time ",
    " theory ": " hypothesis ",
    " there ": " over there ",
    " these ": " these ones ",
    " they ": " they ",
    " thing ": " object ",
    " think ": " consider ",
    " third ": " 3rd ",
    " this ": " this ",
    " those ": " those individuals ",
    " though ": " although ",
    " thought ": " idea ",
    " thousand ": " 1,000 ",
    " three ": " 3 ",
    " through ": " via ",
    " throughout ": " all through ",
    " thus ": " therefore ",
    " time ": " duration ",
    " today ": " presently ",
    " together ": " jointly ",
    " tonight ": " this evening ",
    " too ": " also ",
    " top ": " summit ",
    " toward ": " in the direction of ",
    " town ": " city ",
    " trade ": " commerce ",
    " traditional ": " conventional ",
    " training ": " instruction ",
    " treat ": " address ",
    " treatment ": " therapy ",
    " tree ": " plant ",
    " trial ": " experiment ",
    " trip ": " journey ",
    " trouble ": " difficulty ",
    " truth ": " reality ",
    " turn ": " rotate ",
    " tv ": " television ",
    " two ": " a pair of ",
    " type ": " kind ",
    " under ": " beneath ",
    " understand ": " comprehend ",
    " unit ": " module ",
    " until ": " up to ",
    " upon ": " on ",
    " us ": " we ",
    " use ": " utilize ",
    " usually ": " typically ",
    " various ": " different ",
    " very ": " extremely ",
    " view ": " perspective ",
    " visit ": " go to ",
    " voice ": " sound ",
    " wait ": " wait ",
    " walk ": " stroll ",
    " wall ": " barrier ",
    " want ": " desire ",
    " war ": " conflict ",
    " watch ": " observe ",
    " water ": " liquid ",
    " way ": " method ",
    " we ": " we ",
    " weapon ": " armament ",
    " wear ": " put on ",
    " week ": " 7 days ",
    " weight ": " mass ",
    " well ": " properly ",
    " west ": " western ",
    " what ": " which ",
    " whatever ": " anything ",
    " when ": " at the time of ",
    " where ": " in which place ",
    " whether ": " if ",
    " which ": " which ",
    " white ": " pale ",
    " who ": " individuals who ",
    " whole ": " entire ",
    " whose ": " of whom ",
    " why ": " for what reason ",
    " wide ": " broad ",
    " wife ": " spouse ",
    " will ": " shall ",
    " window ": " pane ",
    " with ": " alongside ",
    " within ": " inside ",
    " without ": " lacking ",
    " woman ": " female ",
    " won't ": " will not ",
    " wonder ": " ponder ",
    " word ": " term ",
    " work ": " job ",
    " worker ": " employee ",
    " world ": " globe ",
    " worry ": " fret ",
    " would ": " prefer ",
    " write ": " scribe ",
    " writer ": " author ",
    " wrong ": " incorrect ",
    " yeah ": " yes ",
    " yes ": " affirmative ",
    " yet ": " still ",
    " you ": " we ",
    " young ": " youthful ",
    " your ": " yours ",
    " yourself ": " your own ",
    " a ": " an ",
    " account ": " ledger ",
    " address ": " location ",
    " admit ": " acknowledge ",
    " agent ": " representative ",
    " agreement ": " accord ",
    " ahead ": " in front ",
    " alone ": " solitary ",
    " assume ": " presume ",
    " at ": " at ",
    " attorney ": " lawyer ",
    " audience ": " spectators ",
    " bag ": " sack ",
    " beat ": " pulse ",
    " born ": " birthed ",
    " budget ": " finances ",
    " cancer ": " carcinoma ",
    " capital ": " city ",
    " cent ": " penny ",
    " citizen ": " resident ",
    " civil ": " civic ",
    " coach ": " mentor ",
    " collection ": " assortment ",
    " commercial ": " business ",
    " compete ": " vie ",
    " consumer ": " buyer ",
    " customer ": " client ",
    " data ": " information ",
    " debate ": " argue ",
    " detail ": " specifics ",
    " differ ": " vary ",
    " dinner ": " supper ",
    " discussion ": " conversation ",
    " exist ": " be ",
    " fast ": " quick ",
    " finger ": " digit ",
    " for ": " in favor of ",
    " gain ": " acquire ",
    " garden ": " yard ",
    " gas ": " fuel ",
    " generation ": " offspring ",
    " heat ": " warmth ",
    " heavy ": " weighty ",
    " hotel ": " inn ",
    " image ": " picture ",
    " interesting ": " intriguing ",
    " investment ": " investment ",
    " item ": " object ",
    " key ": " essential ",
    " kitchen ": " culinary ",
    " let ": " allow ",
    " machine ": " device ",
    " magazine ": " periodical ",
    " majority ": " majority ",
    " marriage ": " matrimony ",
    " method ": " approach ",
    " mission ": " objective ",
    " modern ": " contemporary ",
    " mouth ": " oral cavity ",
    " mrs ": " mrs. ",
    " newspaper ": " journal ",
    " none ": " none ",
    " nor ": " neither ",
    " notice ": " observe ",
    " now ": " at present ",
    " observe ": " watch ",
    " option ": " choice ",
    " owner ": " proprietor ",
    " painting ": " artwork ",
    " participant ": " attendee ",
    " partner ": " companion ",
    " pattern ": " design ",
    " positive ": " affirmative ",
    " press ": " push ",
    " prevent ": " hinder ",
    " professional ": " professional ",
    " purpose ": " aim ",
    " reality ": " actuality ",
    " record ": " document ",
    " reflect ": " ponder ",
    " regard ": " consider ",
    " relate ": " connect ",
    " responsibility ": " obligation ",
    " return ": " give back ",
    " rich ": " wealthy ",
    " right ": " correct ",
    " safe ": " secure ",
    " scientist ": " researcher ",
    " score ": " tally ",
    " senior ": " elderly ",
    " sexual ": " erotic ",
    " shot ": " photograph ",
    " sing ": " vocalize ",
    " skin ": " dermis ",
    " slow ": " sluggish ",
    " smile ": " grin ",
    " soldier ": " servicemember ",
    " somebody ": " someone ",
    " speech ": " oratory ",
    " spirit ": " soul ",
    " succeed ": " accomplish ",
    " successful ": " accomplished ",
    " suffer ": " endure ",
    " surface ": " exterior ",
    " task ": " assignment ",
    " tend ": " incline ",
    " threat ": " menace ",
    " throw ": " toss ",
    " to ": " towards ",
    " total ": " entire ",
    " tough ": " difficult ",
    " travel ": " journey ",
    " true ": " accurate ",
    " unless ": " except if ",
    " up ": " upwards ",
    " value ": " worth ",
    " victim ": " prey ",
    " violence ": " brutality ",
    " vote ": " ballot ",
    " western ": " western ",
    " while ": " whilst ",
    " whom ": " who ",
    " win ": " triumph ",
    " wind ": " breeze ",
    " wish ": " desire ",
    " yard ": " garden ",
    " year ": " 12 months "
}